a= int(input("Please enter value for A="))
b= int(input("Please enter value for B="))

print(f"The numbers entered are {a} {b}. The results are as follows")
print("Addition is",a+b)
print("Subtraction is",a-b)
print("Division is",a/b)
print("Multiplication is",a*b)
print("Integer Division is",a//b)
print("Remainder is", a%b)
print("Exponent is", a**b)